#!/usr/bin/env bash
trap "exit 1" SIGINT
if [[ $# -eq 0 ]]
then
        echo "Specify a drive to format"
        exit 1
fi
DRIVE=$1
PARTITION="$DRIVE""1"
echo $PARTITION
if [[ ! -b $DRIVE ]]
then
        echo "$DRIVE is not a block device"
        exit 1
fi
while true; do
        read -p "Are you sure you want to use $DRIVE? [Y/N]" yn
        case $yn in
                [Yy]* ) break;;
                [Nn]* ) exit 1;;
                * ) echo "Invalid input $yn"
        esac
done
echo "using $DRIVE"
OUTPUT_IMAGE="@LETHE_OUTPUT_FILE@"
if [[ ! -f "$LETHE_OUTPUT_FILE" ]]
then
echo "Failed to build Lethe"
exit 1
fi
sudo dd if=$OUTPUT_IMAGE of=$DRIVE status=progress
