#!/usr/bin/env bash
qemu-system-x86_64 \
-M q35 \
-net none \
-no-reboot \
-no-shutdown \
-enable-kvm \
-cpu host,+invtsc,+syscall \
-m 48G \
-device pci-testdev \
-device pcie-root-port \
-device pcie-pci-bridge \
-device qemu-xhci \
-drive if=pflash,format=raw,readonly=on,unit=0,file=@LETHE_TEST_FW_CODE@ \
-drive if=pflash,format=raw,readonly=on,unit=1,file=@LETHE_TEST_FW_VAR@ \
-drive file=@LETHE_OUTPUT_FILE@ \
-monitor stdio \
-debugcon file:@PROJECT_BINARY_DIR@/templates/log
